# Generated by Django 4.2.5 on 2023-10-13 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cubby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='OrdType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('datePlaced', models.DateField()),
                ('dateCompleted', models.DateField()),
                ('pickupDate', models.DateField()),
                ('cubby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.cubby')),
                ('orderType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.ordtype')),
            ],
        ),
    ]
