# Generated by Django 4.2.5 on 2023-10-14 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='dateCompleted',
        ),
        migrations.AddField(
            model_name='order',
            name='complete',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
