# Generated by Django 4.2.5 on 2023-10-23 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_remove_order_datecompleted_order_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pickupDate',
            field=models.DateField(blank=True),
        ),
    ]
