# Generated by Django 4.2.5 on 2023-10-23 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_alter_order_pickupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pickupDate',
            field=models.DateField(null=True),
        ),
    ]
